# Project information
site_name: Constantinopel RP wet en regelgeving
site_url: 'https://wetboek.constantinopelRP.nl/'
site_description: 'Wet en regelgeving van Constantinopel RP'
site_author: 'Constantinopel RP'

# Copyright
copyright: Copyright &copy; 2022 ConstantinopelRP


# Congiguration
theme:
  name: material
#   features:
#     - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Gebruik dark modus
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Gebruik light modus
  favicon: img/logoConstant.png
  logo: img/logoConstant.png
  custom_dir: docs/overrides
  language: nl
plugins:
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Amsterdam
      locale: nl
      fallback_to_build_date: false
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Overval regels: overvallen.md
  - Wetboek: wetboek.md
  - Kosten:
    - Ambulance: kosten/ambulance.md
    - ANWB: kosten/anwb.md
    - Politie: kosten/politie.md

extra_css:
  - stylesheets/extra.css